import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster";
import "../globals.css";
import { QueryProvider } from "@/lib/react-query/QueryProvider";
import { AuthProvider } from "@/context/AuthContext";
import { Bottombar, LeftSidebar, Topbar } from "@/components/shared";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GitConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/svg+xml" href="/assets/icons/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" type="image/svg+xml" href="/assets/icons/favicon.ico" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex h-screen">
          <QueryProvider>
            <AuthProvider>
              <div className="w-full md:flex">
                <Topbar />
                <LeftSidebar />
                <section className="flex flex-1 h-full">{children}</section>
                <Bottombar />
              </div>
            </AuthProvider>
          </QueryProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
